#!/bin/sh

WORK_DIR="/usr/home/eggs/ovarium/"

# unmount
CMD="umount ${WORK_DIR}.union/upperdir/var"
echo ${CMD}
${CMD}

# cleaning
CMD="rm -rf /usr/home/eggs"
echo ${CMD}
${CMD}

# create mountpoint lower
CMD="mkdir -p ${WORK_DIR}.union/lowerdir/var"
echo ${CMD}
${CMD}

# first: mount /var rw in ${WORK_DIR}.union/lowerdir/var
CMD="mount -t nullfs /var/ ${WORK_DIR}.union/lowerdir/var"
echo ${CMD}
${CHD}

# now remount it ro
CMD="mount -o remount,bind,ro ${WORK_DIR}.union/lowerdir/var"
echo ${CMD}
${CMD}

# second: create mountpoint upper and ${WORK_DIR}filesystem.squashfs and mount var
#mkdir -p ${WORK_DIR}.union/upperdir/var 
#mkdir -p ${WORK_DIR}filesystem.squashfs/var

# thirth: mount /var rw in /home/eggs/ovarium/filesystem.squashfs
